---

language: python

python:
  - 2.7

install:
  - pip install ansible==1.4.0

script:
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
  - >
    ansible-playbook -i inventory playbook.yml 
