---

- name: Create temp folder for heka
  command: mkdir -p -m 0755 {{ heka_temp_path }}

##Debian
- name: Download heka
  get_url:
    dest={{ heka_temp_path }}/{{ heka_package_filename }}
    url={{ heka_mirror }}/v{{ heka_version }}/{{ heka_package_filename }}

- name: Install heka
  command: dpkg -i {{ heka_temp_path }}/{{ heka_package_filename }}

# Install the package "daemon"
- apt: name=daemon state=present

- name: Install hekad service (debian)
  template:
    src=system/hekad_initd.j2
    dest=/etc/init.d/hekad
    owner=0
    group=0
    mode=0755
##END DEBIAN

- name: Create directory
  file: dest={{ heka_hekad_dir }} mode=0755 state=directory

- name: Create Lua directory
  file: dest={{ heka_hekad_lua_dir }} mode=0755 state=directory

- name: Create dashboard directory
  file: dest={{ heka_hekad_cache_dir }}/dashboard mode=0755 state=directory

- name: Create PID directory
  file: dest={{ heka_hekad_pid_dir }} mode=0755 state=directory

- name: Copy monolog.lua
  template:
    src=plugin/monolog.lua
    dest={{ heka_hekad_lua_dir }}/monolog.lua
    owner=0
    group=0
    mode=0644

- name: Install hekad configuration
  notify: service restart hekad
  template:
    src=heka/main.toml.j2
    dest={{ heka_hekad_dir }}/0_hekad_main.toml
    owner=0
    group=0
    mode=0644

- name: Install hekad decoders
  notify: service restart hekad
  with_items: heka_decoders
  template:
    src=decoder/{{ item.type }}.toml.j2
    dest={{ heka_hekad_dir }}/1_{{ item.name }}.toml
    owner=0
    group=0
    mode=0644

- name: Enable Inputs
  notify: service restart hekad
  with_items: heka_inputs
  template:
    src=input/{{ item.type }}.toml.j2
    dest={{ heka_hekad_dir }}/3_{{ item.name }}.toml
    owner=0
    group=0
    mode=0644

- name: Enable outputs
  notify: service restart hekad
  with_items: heka_outputs
  template:
    src=output/{{ item.type }}.toml.j2
    dest={{ heka_hekad_dir }}/4_{{ item.name }}.toml
    owner=0
    group=0
    mode=0644

- name: Enable hekad service
  service:
    enabled=true
    name=hekad

- name: Start hekad service
  service:
    state=started
    name=hekad
